version: "3.9"
services:
  web:
    build: 
      context: ./shopping-list-app
      dockerfile: ./src/ShoppingList.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
      ConnectionStrings__Storage: "http://storage:9000"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - storage
  storage:
    build: 
      context: ./shopping-list-storage
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
      MONGODB_CONNECTION: "mongodb://db:27017"
    depends_on:
      - db
  ddagent: 
    image: datadog/agent:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    #  - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
    links:
     - web 
     - storage 
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
  db:
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data: