version: "3.9"
services:
  web:
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:6.0-bullseye-slim
    ports:
      - "5000:80"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
    command: /bin/sh -c "while sleep 1000; do :; done"
  storage:
    image: mcr.microsoft.com/vscode/devcontainers/go:1.17-bullseye
    ports:
      - "9000:9000"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
    command: /bin/sh -c "while sleep 1000; do :; done"
  ddagent: 
    image: datadog/agent:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
    links:
     - web 
     - storage 
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb-data:

