version: "3.9"
services:
  web:
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:6.0-bullseye
    ports:
      - "5005:80"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
      CORECLR_ENABLE_PROFILING: 1
      CORECLR_PROFILER: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
     - storage
     - otel-collector
  analytyst:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye
    ports:
      - "3000:3000"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
     - rabbitmq
     - otel-collector
  storage:
    image: mcr.microsoft.com/vscode/devcontainers/go:1.18-bullseye
    ports:
      - "9000:9000"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
     - db
     - rabbitmq
     - otel-collector
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  #Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector:0.48.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55679:55679" # zpages extension
      - "4317:4317"
    depends_on:
      - jaeger
      - zipkin
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  mongodb-data:

