version: "3.9"
services:
  web:
    build: 
      context: ./chat-app
      dockerfile: ./src/Chat.App/Dockerfile
    ports:
      - "5000:80"
    environment:
      DD_AGENT_HOST: ddagent
      DD_ENV: "local"
      DD_TRACE_ENABLED: "true"
    depends_on:
      - ddagent
  ddagent: 
    image: gcr.io/datadoghq/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro 
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_APM_ENABLED: "local"

