// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Catalog.Infrastructure.DbContexts
{
    [DbContext(typeof(ProductsDbContext))]
    public partial class ProductsDbContextModel : RuntimeModel
    {
        static ProductsDbContextModel()
        {
            var model = new ProductsDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ProductsDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
