@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/csharp.puml
!include DEVICONS/go.puml
!include DEVICONS/python.puml
!include DEVICONS/mongodb.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(user, "Customer", "Użytkownik", $sprite="users")
Person(analytyst, "Analyst", "Analityk", $sprite="users")

Container(app, "shopping-list-app", "asp net core", "Głowne api do obsługi koszyka", $sprite="csharp")
Container(analytystapi, "shopping-list-analytyst", "Fast Api", "Api zarządzające analityką koszykó", $sprite="python")
Container(storage, "shopping-list-storage", "Go gin", "Adapter na baze danych", $sprite="go")

Container(rabbitmq, "RabbitMq", "amqp", "Kolejka zdarzen")

ContainerDb(db, "Database", "MongoDb", "Holds customer shopping list data", $sprite="mongodb")

Rel(user, app, "Uses", "https")
Rel(app, storage, "Uses", "grpc")
Rel(storage, rabbitmq, "Publikacja zdarzen na koszyku", "amqp")
Rel(rabbitmq, analytystapi, "subskrybcja zdarzen na koszyku", "amqp")
Rel_R(storage, db, "Reads/Writes")
Rel_R(analytystapi, db, "Reads/Writes")
Rel(analytyst, analytystapi, "Uses", "https")
@enduml